

import { Product, ProductStyle, Collection } from './types';

export const PRODUCT_STYLES: ProductStyle[] = ['Modern', 'Classic', 'Minimalist', 'Avant-Garde', 'Natural', 'Industrial'];

export const COLLECTIONS: Collection[] = [
  {
    id: 1,
    name: "Aura Series",
    description: "Where fluidity meets form. The Aura Series embodies the philosophy of water as an art form, with designs that flow seamlessly from aesthetic beauty to functional precision.",
    tagline: "Where fluidity meets form.",
    heroImageUrl: "products/aura/aura-three-mosso.webp",
    style: "Modern",
    products: [
      {
        id: 101,
        name: "Aura Basin Mixer",
        description: "A sleek single-lever basin mixer with a polished chrome finish, designed for modern bathrooms.",
        imageUrl: "products/aura/aura-three-mosso.webp",
        altText: "Aura Basin Mixer - polished chrome single-lever faucet",
        style: "Modern",
        price: 185.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "10\" H x 2\" W" },
          { label: "Flow Rate", value: "1.2 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura101g1/800/1000",
          "https://picsum.photos/seed/aura101g2/800/1000",
          "https://picsum.photos/seed/aura101g3/800/1000",
        ],
      },
      {
        id: 102,
        name: "Aura Tall Boy",
        description: "An elevated tall boy faucet perfect for vessel basins, offering a graceful arc.",
        imageUrl: "https://picsum.photos/seed/aura102/800/1000",
        altText: "Aura Tall Boy - elevated chrome faucet for vessel basins",
        style: "Modern",
        price: 225.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "14\" H x 2\" W" },
          { label: "Flow Rate", value: "1.2 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura102g1/800/1000",
          "https://picsum.photos/seed/aura102g2/800/1000",
        ],
      },
      {
        id: 103,
        name: "Aura Wall Mixer",
        description: "A concealed wall mixer that brings clean lines and minimalist beauty to your shower space.",
        imageUrl: "https://picsum.photos/seed/aura103/800/1000",
        altText: "Aura Wall Mixer - concealed chrome shower mixer",
        style: "Modern",
        price: 165.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "6\" H x 6\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura103g1/800/1000",
          "https://picsum.photos/seed/aura103g2/800/1000",
        ],
      },
      {
        id: 104,
        name: "Aura Shower Set",
        description: "Complete overhead shower system with rain head and handheld combo for the ultimate shower experience.",
        imageUrl: "https://picsum.photos/seed/aura104/800/1000",
        altText: "Aura Shower Set - chrome rain shower system",
        style: "Modern",
        price: 420.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "48\" H x 10\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura104g1/800/1000",
          "https://picsum.photos/seed/aura104g2/800/1000",
        ],
      },
      {
        id: 105,
        name: "Aura Bib Cock",
        description: "A utility bib cock with the signature Aura finish for kitchens and utility areas.",
        imageUrl: "https://picsum.photos/seed/aura105/800/1000",
        altText: "Aura Bib Cock - chrome utility faucet",
        style: "Modern",
        price: 85.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "5\" H x 4\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura105g1/800/1000",
          "https://picsum.photos/seed/aura105g2/800/1000",
        ],
      },
      {
        id: 106,
        name: "Aura Angle Valve",
        description: "Precision-engineered angle valve with quarter-turn ceramic disc for smooth operation.",
        imageUrl: "https://picsum.photos/seed/aura106/800/1000",
        altText: "Aura Angle Valve - chrome angle valve",
        style: "Modern",
        price: 55.00,
        specifications: [
          { label: "Material", value: "Polished Chrome" },
          { label: "Dimensions", value: "3\" H x 2\" W" },
          { label: "Flow Rate", value: "1.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aura106g1/800/1000",
          "https://picsum.photos/seed/aura106g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Metropolis Line",
    description: "Urban elegance redefined. The Metropolis Line draws inspiration from city skylines and architectural marvels, blending luxurious gold finishes with bold structural design.",
    tagline: "Urban elegance redefined.",
    heroImageUrl: "https://picsum.photos/seed/metropolis_hero/1600/800",
    style: "Classic",
    products: [
      {
        id: 201,
        name: "Metropolis Basin Mixer",
        description: "A statement basin mixer in brushed gold, combining classic elegance with modern engineering.",
        imageUrl: "https://picsum.photos/seed/metro201/800/1000",
        altText: "Metropolis Basin Mixer - brushed gold single-lever faucet",
        style: "Classic",
        price: 240.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "11\" H x 6\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Three-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro201g1/800/1000",
          "https://picsum.photos/seed/metro201g2/800/1000",
        ],
      },
      {
        id: 202,
        name: "Metropolis Centre Hole",
        description: "A centre hole basin mixer with dual handles for precise temperature control.",
        imageUrl: "https://picsum.photos/seed/metro202/800/1000",
        altText: "Metropolis Centre Hole - gold dual-handle faucet",
        style: "Classic",
        price: 260.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "10\" H x 8\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Three-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro202g1/800/1000",
          "https://picsum.photos/seed/metro202g2/800/1000",
        ],
      },
      {
        id: 203,
        name: "Metropolis Wall Mixer",
        description: "A luxurious wall-mounted mixer with a brushed gold finish for the discerning homeowner.",
        imageUrl: "https://picsum.photos/seed/metro203/800/1000",
        altText: "Metropolis Wall Mixer - gold wall-mounted mixer",
        style: "Classic",
        price: 210.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "6\" H x 7\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro203g1/800/1000",
          "https://picsum.photos/seed/metro203g2/800/1000",
        ],
      },
      {
        id: 204,
        name: "Metropolis Diverter",
        description: "Five-way diverter with sleek gold handles for multi-outlet shower systems.",
        imageUrl: "https://picsum.photos/seed/metro204/800/1000",
        altText: "Metropolis Diverter - gold five-way shower diverter",
        style: "Classic",
        price: 310.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "6\" H x 6\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro204g1/800/1000",
          "https://picsum.photos/seed/metro204g2/800/1000",
        ],
      },
      {
        id: 205,
        name: "Metropolis Shower Set",
        description: "Premium shower set with gold rain head and adjustable body jets.",
        imageUrl: "https://picsum.photos/seed/metro205/800/1000",
        altText: "Metropolis Shower Set - gold rain shower system",
        style: "Classic",
        price: 520.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "52\" H x 12\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro205g1/800/1000",
          "https://picsum.photos/seed/metro205g2/800/1000",
        ],
      },
      {
        id: 206,
        name: "Metropolis Towel Ring",
        description: "A matching towel ring accessory to complete the Metropolis bathroom aesthetic.",
        imageUrl: "https://picsum.photos/seed/metro206/800/1000",
        altText: "Metropolis Towel Ring - brushed gold towel ring",
        style: "Classic",
        price: 75.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "8\" Diameter" },
          { label: "Weight Capacity", value: "5 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro206g1/800/1000",
          "https://picsum.photos/seed/metro206g2/800/1000",
        ],
      },
      {
        id: 207,
        name: "Metropolis Robe Hook",
        description: "Elegant double robe hook in brushed gold for a harmonious bathroom design.",
        imageUrl: "https://picsum.photos/seed/metro207/800/1000",
        altText: "Metropolis Robe Hook - brushed gold double hook",
        style: "Classic",
        price: 50.00,
        specifications: [
          { label: "Material", value: "Brushed Gold" },
          { label: "Dimensions", value: "3\" H x 3\" W" },
          { label: "Weight Capacity", value: "10 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/metro207g1/800/1000",
          "https://picsum.photos/seed/metro207g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Zenith Collection",
    description: "The essence of simplicity. The Zenith Collection strips away the unnecessary to celebrate pure form and function, finished in a striking matte black.",
    tagline: "The essence of simplicity.",
    heroImageUrl: "https://picsum.photos/seed/zenith_hero/1600/800",
    style: "Minimalist",
    products: [
      {
        id: 301,
        name: "Zenith Basin Mixer",
        description: "Clean-lined basin mixer in matte black, the centerpiece of minimalist design.",
        imageUrl: "https://picsum.photos/seed/zenith301/800/1000",
        altText: "Zenith Basin Mixer - matte black single lever faucet",
        style: "Minimalist",
        price: 195.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Dimensions", value: "9.5\" H x 2.5\" W" },
          { label: "Flow Rate", value: "1.0 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith301g1/800/1000",
          "https://picsum.photos/seed/zenith301g2/800/1000",
        ],
      },
      {
        id: 302,
        name: "Zenith Tall Boy",
        description: "Elevated matte black faucet for vessel sinks with a slender, architectural profile.",
        imageUrl: "https://picsum.photos/seed/zenith302/800/1000",
        altText: "Zenith Tall Boy - matte black tall vessel faucet",
        style: "Minimalist",
        price: 235.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Dimensions", value: "13\" H x 2\" W" },
          { label: "Flow Rate", value: "1.0 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith302g1/800/1000",
          "https://picsum.photos/seed/zenith302g2/800/1000",
        ],
      },
      {
        id: 303,
        name: "Zenith Concealed Diverter",
        description: "Flush-mount concealed diverter for a seamless shower wall aesthetic.",
        imageUrl: "https://picsum.photos/seed/zenith303/800/1000",
        altText: "Zenith Concealed Diverter - matte black flush diverter",
        style: "Minimalist",
        price: 280.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Dimensions", value: "6\" x 6\" Plate" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Concealed" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith303g1/800/1000",
          "https://picsum.photos/seed/zenith303g2/800/1000",
        ],
      },
      {
        id: 304,
        name: "Zenith Rain Shower",
        description: "Ultra-slim 300mm rain shower head that delivers a drenching waterfall effect.",
        imageUrl: "https://picsum.photos/seed/zenith304/800/1000",
        altText: "Zenith Rain Shower - matte black overhead rain head",
        style: "Minimalist",
        price: 350.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Dimensions", value: "12\" Diameter" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Ceiling-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith304g1/800/1000",
          "https://picsum.photos/seed/zenith304g2/800/1000",
        ],
      },
      {
        id: 305,
        name: "Zenith Health Faucet",
        description: "Ergonomic handheld health faucet with a smooth trigger and black silicone grip.",
        imageUrl: "https://picsum.photos/seed/zenith305/800/1000",
        altText: "Zenith Health Faucet - matte black handheld spray",
        style: "Minimalist",
        price: 65.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Dimensions", value: "7\" L" },
          { label: "Flow Rate", value: "1.2 GPM" },
          { label: "Installation", value: "Wall-mounted hook" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith305g1/800/1000",
          "https://picsum.photos/seed/zenith305g2/800/1000",
        ],
      },
      {
        id: 306,
        name: "Zenith Soap Dispenser",
        description: "Built-in counter soap dispenser with matte black pump for a unified look.",
        imageUrl: "https://picsum.photos/seed/zenith306/800/1000",
        altText: "Zenith Soap Dispenser - matte black counter dispenser",
        style: "Minimalist",
        price: 45.00,
        specifications: [
          { label: "Material", value: "Matte Black Finish" },
          { label: "Capacity", value: "350ml" },
          { label: "Dimensions", value: "8\" H x 2.5\" W" },
          { label: "Installation", value: "Counter-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/zenith306g1/800/1000",
          "https://picsum.photos/seed/zenith306g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Terra Collection",
    description: "Inspired by natural earth tones. The Terra Collection brings the warmth and beauty of nature indoors with its signature brushed bronze finish and organic shapes.",
    tagline: "Inspired by natural earth tones.",
    heroImageUrl: "https://picsum.photos/seed/terra_hero/1600/800",
    style: "Natural",
    products: [
      {
        id: 401,
        name: "Terra Basin Mixer",
        description: "Warm brushed bronze basin mixer that complements natural stone and wood surfaces.",
        imageUrl: "https://picsum.photos/seed/terra401/800/1000",
        altText: "Terra Basin Mixer - brushed bronze basin faucet",
        style: "Natural",
        price: 210.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "10.5\" H x 3\" W" },
          { label: "Flow Rate", value: "1.2 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra401g1/800/1000",
          "https://picsum.photos/seed/terra401g2/800/1000",
        ],
      },
      {
        id: 402,
        name: "Terra Wall Mixer",
        description: "Bronze wall mixer with a waterfall spout, evoking the serenity of natural springs.",
        imageUrl: "https://picsum.photos/seed/terra402/800/1000",
        altText: "Terra Wall Mixer - bronze waterfall wall mixer",
        style: "Natural",
        price: 190.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "7\" H x 8\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra402g1/800/1000",
          "https://picsum.photos/seed/terra402g2/800/1000",
        ],
      },
      {
        id: 403,
        name: "Terra Kitchen Mixer",
        description: "Pull-out kitchen mixer in bronze, designed for everyday tasks with effortless style.",
        imageUrl: "https://picsum.photos/seed/terra403/800/1000",
        altText: "Terra Kitchen Mixer - bronze pull-out kitchen faucet",
        style: "Natural",
        price: 275.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "16\" H x 9\" W" },
          { label: "Flow Rate", value: "1.8 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra403g1/800/1000",
          "https://picsum.photos/seed/terra403g2/800/1000",
        ],
      },
      {
        id: 404,
        name: "Terra Shower Panel",
        description: "Multi-function shower panel with bronze finish, body jets, and handheld shower.",
        imageUrl: "https://picsum.photos/seed/terra404/800/1000",
        altText: "Terra Shower Panel - bronze multi-function panel",
        style: "Natural",
        price: 580.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "60\" H x 8\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra404g1/800/1000",
          "https://picsum.photos/seed/terra404g2/800/1000",
        ],
      },
      {
        id: 405,
        name: "Terra Towel Bar",
        description: "Sturdy 24-inch towel bar in brushed bronze with a subtly textured grip surface.",
        imageUrl: "https://picsum.photos/seed/terra405/800/1000",
        altText: "Terra Towel Bar - bronze 24-inch bar",
        style: "Natural",
        price: 90.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "24\" W x 3\" D" },
          { label: "Weight Capacity", value: "10 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra405g1/800/1000",
          "https://picsum.photos/seed/terra405g2/800/1000",
        ],
      },
      {
        id: 406,
        name: "Terra Tissue Holder",
        description: "Wall-mounted toilet tissue holder with a covered design in brushed bronze.",
        imageUrl: "https://picsum.photos/seed/terra406/800/1000",
        altText: "Terra Tissue Holder - bronze wall tissue holder",
        style: "Natural",
        price: 55.00,
        specifications: [
          { label: "Material", value: "Brushed Bronze" },
          { label: "Dimensions", value: "6\" W x 4\" H" },
          { label: "Weight", value: "0.8 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/terra406g1/800/1000",
          "https://picsum.photos/seed/terra406g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Aqua Line",
    description: "Purity in every drop. The Aqua Line pushes design boundaries with transparent acrylic elements and chrome accents, creating faucets that are as much sculpture as function.",
    tagline: "Purity in every drop.",
    heroImageUrl: "https://picsum.photos/seed/aqua_hero/1600/800",
    style: "Avant-Garde",
    products: [
      {
        id: 501,
        name: "Aqua Basin Mixer",
        description: "Transparent acrylic and chrome basin mixer that reveals the beauty of flowing water.",
        imageUrl: "https://picsum.photos/seed/aqua501/800/1000",
        altText: "Aqua Basin Mixer - transparent acrylic and chrome faucet",
        style: "Avant-Garde",
        price: 280.00,
        specifications: [
          { label: "Material", value: "Acrylic & Chrome" },
          { label: "Dimensions", value: "12\" H x 4\" W" },
          { label: "Flow Rate", value: "1.8 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua501g1/800/1000",
          "https://picsum.photos/seed/aqua501g2/800/1000",
        ],
      },
      {
        id: 502,
        name: "Aqua LED Mixer",
        description: "Temperature-sensitive LED faucet that changes color from blue to red with water temperature.",
        imageUrl: "https://picsum.photos/seed/aqua502/800/1000",
        altText: "Aqua LED Mixer - LED temperature-indicating faucet",
        style: "Avant-Garde",
        price: 340.00,
        specifications: [
          { label: "Material", value: "Chrome & LED Array" },
          { label: "Dimensions", value: "11\" H x 3\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua502g1/800/1000",
          "https://picsum.photos/seed/aqua502g2/800/1000",
        ],
      },
      {
        id: 503,
        name: "Aqua Waterfall Spout",
        description: "Wide-mouth waterfall spout that creates a stunning sheet of water for a dramatic effect.",
        imageUrl: "https://picsum.photos/seed/aqua503/800/1000",
        altText: "Aqua Waterfall Spout - wide-mouth cascade faucet",
        style: "Avant-Garde",
        price: 310.00,
        specifications: [
          { label: "Material", value: "Glass & Chrome" },
          { label: "Dimensions", value: "8\" H x 6\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua503g1/800/1000",
          "https://picsum.photos/seed/aqua503g2/800/1000",
        ],
      },
      {
        id: 504,
        name: "Aqua Sensor Faucet",
        description: "Touchless infrared sensor faucet with adjustable auto-off timer for water conservation.",
        imageUrl: "https://picsum.photos/seed/aqua504/800/1000",
        altText: "Aqua Sensor Faucet - touchless infrared faucet",
        style: "Avant-Garde",
        price: 400.00,
        specifications: [
          { label: "Material", value: "Chrome & Sensor" },
          { label: "Dimensions", value: "10\" H x 3\" W" },
          { label: "Flow Rate", value: "1.0 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua504g1/800/1000",
          "https://picsum.photos/seed/aqua504g2/800/1000",
        ],
      },
      {
        id: 505,
        name: "Aqua Bathtub Filler",
        description: "Freestanding floor-mounted bathtub filler with an acrylic handle and chrome body.",
        imageUrl: "https://picsum.photos/seed/aqua505/800/1000",
        altText: "Aqua Bathtub Filler - freestanding chrome tub faucet",
        style: "Avant-Garde",
        price: 680.00,
        specifications: [
          { label: "Material", value: "Acrylic & Chrome" },
          { label: "Dimensions", value: "36\" H x 8\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Floor-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua505g1/800/1000",
          "https://picsum.photos/seed/aqua505g2/800/1000",
        ],
      },
      {
        id: 506,
        name: "Aqua Shower Head",
        description: "Multi-pattern shower head with transparent body showing internal water flow channels.",
        imageUrl: "https://picsum.photos/seed/aqua506/800/1000",
        altText: "Aqua Shower Head - transparent multi-pattern head",
        style: "Avant-Garde",
        price: 150.00,
        specifications: [
          { label: "Material", value: "Clear Acrylic & Chrome" },
          { label: "Dimensions", value: "8\" Diameter" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Wall-mounted arm" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/aqua506g1/800/1000",
          "https://picsum.photos/seed/aqua506g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 6,
    name: "Etherea Series",
    description: "Lightweight and timeless design. The Etherea Series achieves visual weightlessness through impossibly thin spouts and floating aesthetics, finished in sophisticated brushed nickel.",
    tagline: "Lightweight and timeless design.",
    heroImageUrl: "https://picsum.photos/seed/etherea_hero/1600/800",
    style: "Minimalist",
    products: [
      {
        id: 601,
        name: "Etherea Basin Mixer",
        description: "Ultra-thin spout basin mixer in brushed nickel with a barely-there aesthetic.",
        imageUrl: "https://picsum.photos/seed/etherea601/800/1000",
        altText: "Etherea Basin Mixer - brushed nickel thin-spout faucet",
        style: "Minimalist",
        price: 220.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "11.5\" H x 2\" W" },
          { label: "Flow Rate", value: "1.2 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea601g1/800/1000",
          "https://picsum.photos/seed/etherea601g2/800/1000",
        ],
      },
      {
        id: 602,
        name: "Etherea Concealed Mixer",
        description: "Flush-mounted concealed mixer with a slim nickel plate for a clean wall surface.",
        imageUrl: "https://picsum.photos/seed/etherea602/800/1000",
        altText: "Etherea Concealed Mixer - brushed nickel flush mixer",
        style: "Minimalist",
        price: 195.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "5\" x 5\" Plate" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Concealed" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea602g1/800/1000",
          "https://picsum.photos/seed/etherea602g2/800/1000",
        ],
      },
      {
        id: 603,
        name: "Etherea Shower Arm",
        description: "Slim wall-mount shower arm with a seamless transition to the shower head.",
        imageUrl: "https://picsum.photos/seed/etherea603/800/1000",
        altText: "Etherea Shower Arm - brushed nickel slim arm",
        style: "Minimalist",
        price: 85.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "15\" L" },
          { label: "Thread Size", value: "1/2\" NPT" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea603g1/800/1000",
          "https://picsum.photos/seed/etherea603g2/800/1000",
        ],
      },
      {
        id: 604,
        name: "Etherea Hand Shower",
        description: "Lightweight handheld shower with three spray modes and a flexible hose.",
        imageUrl: "https://picsum.photos/seed/etherea604/800/1000",
        altText: "Etherea Hand Shower - brushed nickel handheld",
        style: "Minimalist",
        price: 120.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "10\" L" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Hose-connected" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea604g1/800/1000",
          "https://picsum.photos/seed/etherea604g2/800/1000",
        ],
      },
      {
        id: 605,
        name: "Etherea Shelf Mixer",
        description: "Integrated wall mixer with a built-in shelf for soap or toiletries — form meets function.",
        imageUrl: "https://picsum.photos/seed/etherea605/800/1000",
        altText: "Etherea Shelf Mixer - brushed nickel mixer with shelf",
        style: "Minimalist",
        price: 260.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "8\" H x 12\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea605g1/800/1000",
          "https://picsum.photos/seed/etherea605g2/800/1000",
        ],
      },
      {
        id: 606,
        name: "Etherea Angle Valve",
        description: "Slim angle valve designed to sit flush with the wall, continuing the series' minimal profile.",
        imageUrl: "https://picsum.photos/seed/etherea606/800/1000",
        altText: "Etherea Angle Valve - brushed nickel slim valve",
        style: "Minimalist",
        price: 48.00,
        specifications: [
          { label: "Material", value: "Brushed Nickel" },
          { label: "Dimensions", value: "3\" H x 2\" W" },
          { label: "Flow Rate", value: "1.0 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/etherea606g1/800/1000",
          "https://picsum.photos/seed/etherea606g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 7,
    name: "Heritage Range",
    description: "Timeless elegance, crafted for today. The Heritage Range pays homage to classic European design with ornate cross handles and polished nickel, marrying tradition with modern reliability.",
    tagline: "Timeless elegance, crafted for today.",
    heroImageUrl: "https://picsum.photos/seed/heritage_hero/1600/800",
    style: "Classic",
    products: [
      {
        id: 701,
        name: "Heritage Basin Set",
        description: "Three-hole widespread basin set with cross handles, a tribute to classic design.",
        imageUrl: "https://picsum.photos/seed/heritage701/800/1000",
        altText: "Heritage Basin Set - polished nickel widespread faucet",
        style: "Classic",
        price: 260.00,
        specifications: [
          { label: "Material", value: "Polished Nickel" },
          { label: "Dimensions", value: "9\" H x 7\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Widespread" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage701g1/800/1000",
          "https://picsum.photos/seed/heritage701g2/800/1000",
        ],
      },
      {
        id: 702,
        name: "Heritage Centre Hole",
        description: "Single-hole centre-set mixer with a classic arched spout and cross handle.",
        imageUrl: "https://picsum.photos/seed/heritage702/800/1000",
        altText: "Heritage Centre Hole - polished nickel arched faucet",
        style: "Classic",
        price: 230.00,
        specifications: [
          { label: "Material", value: "Polished Nickel" },
          { label: "Dimensions", value: "10\" H x 5\" W" },
          { label: "Flow Rate", value: "1.5 GPM" },
          { label: "Installation", value: "Single-hole" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage702g1/800/1000",
          "https://picsum.photos/seed/heritage702g2/800/1000",
        ],
      },
      {
        id: 703,
        name: "Heritage Shower Mixer",
        description: "Exposed thermostatic shower mixer with dual cross handles and a traditional slider rail.",
        imageUrl: "https://picsum.photos/seed/heritage703/800/1000",
        altText: "Heritage Shower Mixer - polished nickel thermostatic mixer",
        style: "Classic",
        price: 380.00,
        specifications: [
          { label: "Material", value: "Polished Nickel" },
          { label: "Dimensions", value: "42\" H x 6\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Exposed wall-mount" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage703g1/800/1000",
          "https://picsum.photos/seed/heritage703g2/800/1000",
        ],
      },
      {
        id: 704,
        name: "Heritage Bathtub Filler",
        description: "Freestanding bath filler with cross handles and a telephone-style hand shower.",
        imageUrl: "https://picsum.photos/seed/heritage704/800/1000",
        altText: "Heritage Bathtub Filler - polished nickel freestanding tub faucet",
        style: "Classic",
        price: 720.00,
        specifications: [
          { label: "Material", value: "Polished Nickel" },
          { label: "Dimensions", value: "38\" H x 8\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Floor-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage704g1/800/1000",
          "https://picsum.photos/seed/heritage704g2/800/1000",
        ],
      },
      {
        id: 705,
        name: "Heritage Towel Rail",
        description: "Double towel rail with ornate brackets in polished nickel, 24 inches wide.",
        imageUrl: "https://picsum.photos/seed/heritage705/800/1000",
        altText: "Heritage Towel Rail - polished nickel double rail",
        style: "Classic",
        price: 110.00,
        specifications: [
          { label: "Material", value: "Polished Nickel" },
          { label: "Dimensions", value: "24\" W x 6\" D" },
          { label: "Weight Capacity", value: "15 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage705g1/800/1000",
          "https://picsum.photos/seed/heritage705g2/800/1000",
        ],
      },
      {
        id: 706,
        name: "Heritage Soap Dish",
        description: "Wall-mounted soap dish with a glass tray and ornamental nickel bracket.",
        imageUrl: "https://picsum.photos/seed/heritage706/800/1000",
        altText: "Heritage Soap Dish - polished nickel and glass soap dish",
        style: "Classic",
        price: 45.00,
        specifications: [
          { label: "Material", value: "Polished Nickel & Glass" },
          { label: "Dimensions", value: "6\" W x 4\" D" },
          { label: "Weight", value: "0.5 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/heritage706g1/800/1000",
          "https://picsum.photos/seed/heritage706g2/800/1000",
        ],
      },
    ],
  },
  {
    id: 8,
    name: "Forge Collection",
    description: "Bold, industrial, and unapologetic. The Forge Collection celebrates raw materials and exposed mechanisms, bringing the rugged beauty of the workshop into the bathroom.",
    tagline: "Bold, industrial, and unapologetic.",
    heroImageUrl: "https://picsum.photos/seed/forge_hero/1600/800",
    style: "Industrial",
    products: [
      {
        id: 801,
        name: "Forge Basin Tap",
        description: "Exposed pipework basin tap in raw metal with a pipe-style spout and wheel handle.",
        imageUrl: "https://picsum.photos/seed/forge801/800/1000",
        altText: "Forge Basin Tap - raw metal industrial faucet",
        style: "Industrial",
        price: 200.00,
        specifications: [
          { label: "Material", value: "Raw Metal Finish" },
          { label: "Dimensions", value: "13\" H x 5\" W" },
          { label: "Flow Rate", value: "1.8 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge801g1/800/1000",
          "https://picsum.photos/seed/forge801g2/800/1000",
        ],
      },
      {
        id: 802,
        name: "Forge Wall Tap",
        description: "Wall-mounted industrial tap with exposed copper pipes and a matte iron body.",
        imageUrl: "https://picsum.photos/seed/forge802/800/1000",
        altText: "Forge Wall Tap - exposed copper and iron wall faucet",
        style: "Industrial",
        price: 185.00,
        specifications: [
          { label: "Material", value: "Iron & Copper" },
          { label: "Dimensions", value: "10\" H x 6\" W" },
          { label: "Flow Rate", value: "1.8 GPM" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge802g1/800/1000",
          "https://picsum.photos/seed/forge802g2/800/1000",
        ],
      },
      {
        id: 803,
        name: "Forge Shower System",
        description: "Full industrial shower system with exposed pipes, wheel-handle controls, and a large rain head.",
        imageUrl: "https://picsum.photos/seed/forge803/800/1000",
        altText: "Forge Shower System - industrial exposed pipe shower",
        style: "Industrial",
        price: 550.00,
        specifications: [
          { label: "Material", value: "Raw Metal & Iron" },
          { label: "Dimensions", value: "56\" H x 10\" W" },
          { label: "Flow Rate", value: "2.5 GPM" },
          { label: "Installation", value: "Exposed wall-mount" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge803g1/800/1000",
          "https://picsum.photos/seed/forge803g2/800/1000",
        ],
      },
      {
        id: 804,
        name: "Forge Kitchen Tap",
        description: "Heavy-duty kitchen tap with a coiled spring spout and industrial pull-down spray.",
        imageUrl: "https://picsum.photos/seed/forge804/800/1000",
        altText: "Forge Kitchen Tap - industrial coil spring kitchen faucet",
        style: "Industrial",
        price: 320.00,
        specifications: [
          { label: "Material", value: "Gunmetal & Steel" },
          { label: "Dimensions", value: "18\" H x 9\" W" },
          { label: "Flow Rate", value: "2.0 GPM" },
          { label: "Installation", value: "Deck-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge804g1/800/1000",
          "https://picsum.photos/seed/forge804g2/800/1000",
        ],
      },
      {
        id: 805,
        name: "Forge Pipe Shelf",
        description: "Wall-mounted pipe shelf with three tiers for bathroom storage — pure industrial style.",
        imageUrl: "https://picsum.photos/seed/forge805/800/1000",
        altText: "Forge Pipe Shelf - industrial three-tier pipe shelf",
        style: "Industrial",
        price: 160.00,
        specifications: [
          { label: "Material", value: "Iron Pipe & Wood" },
          { label: "Dimensions", value: "24\" H x 20\" W" },
          { label: "Weight Capacity", value: "30 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge805g1/800/1000",
          "https://picsum.photos/seed/forge805g2/800/1000",
        ],
      },
      {
        id: 806,
        name: "Forge Toilet Roll Holder",
        description: "Pipe-style toilet roll holder in raw iron, a small detail that ties the room together.",
        imageUrl: "https://picsum.photos/seed/forge806/800/1000",
        altText: "Forge Toilet Roll Holder - iron pipe toilet paper holder",
        style: "Industrial",
        price: 40.00,
        specifications: [
          { label: "Material", value: "Raw Iron Pipe" },
          { label: "Dimensions", value: "7\" L x 4\" D" },
          { label: "Weight", value: "1.2 lbs" },
          { label: "Installation", value: "Wall-mounted" },
        ],
        galleryImages: [
          "https://picsum.photos/seed/forge806g1/800/1000",
          "https://picsum.photos/seed/forge806g2/800/1000",
        ],
      },
    ],
  },
];

// Flat list of all products across all collections (for backward compatibility and search)
export const PRODUCTS: Product[] = COLLECTIONS.flatMap(c => c.products);